### PR TITLE
Strip trailing whitespace

### PR DESCRIPTION
**Pull request by angstsmurf**
This probably increases the size of the Git repository again by quite a bit. I've tried to restrict the changes to the common C and C++ source files.

### CODE REVIEW

**Comment by curiousdannii** [comment]
I'd said no more rewriting the history, but maybe this would be okay. On the other hand, it might just not be worth it at all, and we could just fix the trailing spaces as we go.

**Comment by realnc** [comment]
Please don't. These things make it harder to cherry pick upstream fixes (I fixed some bugs over the years in the base code, and Mike Roberts also sent me a couple fixes a few years ago.) Whitespace changes will result in a desync with upstream and thus there's gonna be merge conflicts.

**Comment by angstsmurf** [comment]
Not much different from changing line endings in that respect. Most tools have settings to ignore whitespace.

Anyway, I'll close this.

**Comment by realnc** [comment]
> Not much different from changing line endings in that respect. Most tools have settings to ignore whitespace.
> 
> Anyway, I'll close this.

It's just that if Mike Roberts ever decides to pick up Tads development again, it will be easier to sync if we keep the sources as unmodified as possible because Mike doesn't use git, he just distributes the sources as zip files.

The line endings are an exception because when extracting the zip files, you just use `unzip -a`, which automatically converts line endings. That's why it's fine to have Unix line endings in the repo :)

**Comment by curiousdannii** [comment]
I hadn't noticed this before, but the first few commits here add and remove all the source code like three times. Though if Git compresses them smartly this might not actually make a difference to the repository clone size.

**Pull request closed without merging**
