### PR TITLE
Start fixing Glk banner colours: don't use measured colours (#3)

### PR DESCRIPTION
**Pull request by curiousdannii**
Started fixing #3.

I've removed the mainfg/bg colours as we don't need them.

`os_banner_set_screen_color` doesn't do anything now, so need to work out a better solution for it. Anyone got an example story that uses it?

### CODE REVIEW

**Comment by angstsmurf** [comment]
[The Devil in the Details](https://ifdb.org/viewgame?id=fsa1bze0pnwqmm4z) uses `os_banner_set_screen_color`.

**Comment by curiousdannii** [comment]
Thanks.

I just noticed this would make your invisible character solution not work. So I don't know... maybe setting black on white would be better.

**Comment by angstsmurf** [comment]
I really couldn't say. I'm still trying to figure out how to make Spatterlight compile with this code. There are probably simpler ways to test it.

But it seems to me that replacing  characters with spaces would be the only way to make TADS 3 menus usable on Glk interpreters without styles support.

**Comment by curiousdannii** [comment]
Okay. I'll try for that first, see if it works reliably enough.

**Comment by curiousdannii** [comment]
> [The Devil in the Details](https://ifdb.org/viewgame?id=fsa1bze0pnwqmm4z) uses `os_banner_set_screen_color`.

Is it just the direction colours in the status window, or something else too?

**Comment by curiousdannii** [comment]
Accidentally merged this into master instead of the parchment branch, though have now reverted that. Please consider this still under review.

**Pull request merged**
